### ISSUE TITLE
Avoid app breakage

### ISSUE THREAD

**Issue by kasnder** [OxfordHCC/tracker-control-android#128]
A major barrier for non-techies remains the breakage of apps.

I've introduce a non-strict mode to make this easier. There's certainly room to improve this.

A Twitter user suggested notifications on first blocking of app communications, besides potentially more granular filtering. I like the idea but don't want to burden the user with notifications.

One way would be to send a few notifications to make the user aware of the fact that things may break with new apps.

**Comment by Hydroo24** [comment]
Hey! More granular filtering would be nice.
For example in YouTube, I must unblock everything in Essential because all are from Google. However, only one unlock may be sufficient.
A whitelist for global domains would also help. 
![Screenshot_20201208-163154_TrackerControl](https://user-images.githubusercontent.com/45118588/101504129-27ff5800-3973-11eb-9eb0-5f1731db1fb2.png)

**Comment by kasnder** [comment]
Thanks for reporting this. Did you have to unblock anything else but what was in 'Essential'?

**Comment by Hydroo24** [comment]
For YouTube I had to disable everything. But looking you can get an idea of what is really necessary when you use uBlock Origin : 
![Screenshot_20201208-202644_Firefox](https://user-images.githubusercontent.com/45118588/101531580-c3a0c080-3993-11eb-8bce-d1446df734f0.png)

**Comment by kasnder** [comment]
I guess, I'd need to re-categorise some stuff as 'Essential'.

**Comment by kasnder** [comment]
This is addressed in #147
