### ISSUE TITLE
[Feature] Dark theme

### ISSUE THREAD

**Issue by Atrate** [OxfordHCC/tracker-control-android#19]
It would be pretty nice to have a dark theme.

I can also try to make a PR for that, but be aware that it would be my first time trying to implement theming in an app.

**Comment by kasnder** [comment]
This is a great suggestion. Thank you for that. UI is currently not my priority, I’m focusing on good tracker detection.

The implementation of a dark themes should be without major hurdles, since TrackerControl borrows much code from NetGuard, which has dark themes.

The themes, including dark themes, are defined in the file: https://github.com/OxfordHCC/tracker-control-android/blob/master/app/src/main/res/values/styles.xml

I’ve removed the theming functionality from the preferences screen here: https://github.com/OxfordHCC/tracker-control-android/blob/929d37efa74b96623125ef374866f7d169578861/app/src/main/java/eu/faircode/netguard/ActivitySettings.java#L407

I’ve done this because added many new components to NetGuard, which may not support these themes. These components would have to be changed. In addition, theming is a paid-for functionality in NetGuard, which I didn’t just want to copy and put out for free.

If you were to add solely a dark theme, this seems like a very valuable addition.

**Comment by MegaArthur** [comment]
If I get some time I'll try to spin something up but not promising anything

**Comment by kasnder** [comment]
Sure, that’s very fair!

**Comment by Atrate** [comment]
I have to say I can't implement the dark theme due to a lack of time, sorry

**Comment by kasnder** [comment]
No worries. Thanks for letting me know. :)

**Comment by kasnder** [comment]
This has been added now in the latest release. Would love to hear your feedback, @Atrate. The colours aren't perfect yet, but otherwise it should functional!

**Comment by Atrate** [comment]
And where can I activate that? I can't see a switch in the options menu

**Comment by kasnder** [comment]
It’s a switch in the settings so far! First list entry!

**Comment by kasnder** [comment]
Closing this for now.
