### ISSUE TITLE
[Feature] Add app tracker details

### ISSUE THREAD

**Issue by Atrate** [OxfordHCC/tracker-control-android#20]
Exodus is a FOSS app+web service dedicated to detecting code signatures belonging to certain trackers and showing their detailed descriptions.

This app could probably use its resources, be it just for detailed info or even for automatic on-demand analysis of installed apps.

https://exodus-privacy.eu.org/en/

https://f-droid.org/app/org.eu.exodus_privacy.exodusprivacy

**Comment by kasnder** [comment]
I agree though that more information about trackers is much needed.

I’ve been thinking about including information from AppBrain, Ghostery, or the Guardian. They all offer detailed information about trackers, such as:

- https://www.appbrain.com/stats/libraries/details/admob/admob
- https://www.theguardian.com/technology/2012/apr/23/quantcast-tracking-trackers-cookies-web-monitoring
- https://apps.ghostery.com/en/apps/google_analytics

Since TrackedControl currently works on tracker domains and not with signatures of libraries, merging Exodus information could be challenging.

_Were you thinking of any specific resources from Exodus?_

**Comment by MegaArthur** [comment]
The app could for example grab updated data about trackers from https://reports.exodus-privacy.eu.org/en/ and even submit APKs for analysis if the user agrees

**Comment by kasnder** [comment]
A little update: What I’ll soon do is switch to the tracking list behind Mozilla Firefox. This will additionally offer 1) a categorisation (e.g. ads, analytics), and 2) a link to the webpage of the tracker company.

**Comment by kasnder** [comment]
I've now added this to the latest release. Let me know what you think!
