### ISSUE TITLE
Questions about function and usage of TrackerControl

### ISSUE THREAD

**Issue by bege10** [OxfordHCC/tracker-control-android#22]
I have a few questions:

1. What database uses TC? I only found very small databases in the app data and the downloaded hosts file seems not to be used, the URLs are not being blocked. By now I used AdAway. It needs very little RAM. The advantage of TC is that I can block domains per app. Is it possible to combine AdAway and TC? E.g. Add the tracker domains from TC to AdAway or use the lists from AdAway in TC?
2. What is IP filtering necessary for?
3. What is "Block domain names" in advanced settings for?
4. Which domain names are listed in "Show resolved domain names"? The blocked ones? Any connected domain? Is it possible to see which app connected to which domain?
5. At least one app (BusinessCalendar2) cannot connect to the internet if the Block switch in the general UI is on. What may be the reason?
6. TC does not start when booting the phone. Is that intentionally? I can live well with this because mostly I am offline. I use Tasker to start and stop TC. That saves RAM when I am offline.

**Comment by kasnder** [comment]
Thanks for the comprehensive feedback! I hope you like the app. :)

1. Currently, it uses a database from a research project, that even allows to disclose the corporate structure behind tracking (some tracker companies belong to other tracker companies). Since this is mostly relevant for research purposes, I will soon switch to the Disconnect tracker list, also used in Firefox. This will allow for even better tracking, and additionally disclose the nature of tracking, such as advertising or analytics.
2. There are two ways to block communications to domains, either blocking based on IP addresses (which allows for easy association with the responsible app), or blocking based on DNS requests (which saves energy but makes attribution to apps more difficult). TrackerControl uses IP-based filtering, translating all IP communications into domain names, and checking against the tracker database in (1.).
3. TrackerControl alternatively offers blocking of DNS requests, as described above in (2.). This even supports blocking lists from AdAway, at the expense of fine-grained attribution to apps. More information here: https://github.com/OxfordHCC/tracker-control-android/blob/master/ADBLOCKING.md
4. All domains. Currently, there's no UI, but you can "Export as CSV" from menu on the app details screen.
5. I'm sorry.. I'll check that, thanks! You can always bypass TrackerControl for certain apps, by disabling blocking from the main menu for specific apps.
6. Strange. It should start automatically, if it is turned on before shutting down. There might be a conflict with Tasker.

**Comment by bege10** [comment]
Thank you for your detailed answer. Yes, I like the idea and the make of the app. I am grateful for your work. It's a Android -:umbrella:

1. Where is that database stored on the device? I don't find it. Or does TC check online?
The new version of TC only finds very few domains. How does TC work if I visit a URL with a browser when the URL contains many trackers. Should they appear in TC with the browser? Currently the browsers don't show any trackers.
2. You say "easy" and "difficult". As I understand IP-filtering increases battery usage. Can TC block per app without IP-filtering?
3. What does "at the expense of" mean? Other than AdAway TC can use hosts list per app or it loses the ability to block per app if using hosts lists?
4. Does "currently" mean that you consider adding a UI? AdAway also shows which domains have been blocked and which not. I'd appreciate that feature very much in TC. The respective app would be very helpful also.
5. BusinessCalendar2 allows to download school holiday calendars. This only works if I deactivate blocking for that app in TC. There are no trackers listed for that app in TC.
Additionally ProfiMail Go (mail client) does not connect correctly to t-online.de (IMAP, starts with a few folders and then hangs) and not at all to gmx.de (POP3, but there is a tracker listed for United Internet Media which hosts GMX). After deactivating blocking in TC all accounts work correct.
6. I was wrong. TC starts but not the VPN. But that starts with the first internet connection. As long as I don't open the UI of TC the RAM usage is even lower (below 20MB)  :thumbsup:

**Comment by kasnder** [comment]
1. I now use additionally the Disconnect tracker database, that is also used by the Firefox browser. :)
2. Yes, that's what the ad-blocking feature in the settings does. I don't actively support this though; it's just borrowed from the NetGuard firewall.
3. You lose the ability to block by app. I don't like this, which is why I don't actively support it (see 2.).
4. I meant that there's no overview of blocked domains currently in the app. May add it at a later stage! Want to keep it simple..
5. Strange, thanks for reporting this. I'll look into it. #23
6. Oh, that's good news, for once! :)
