### ISSUE TITLE
Add Private DNS

### ISSUE THREAD

**Issue by kasnder** [OxfordHCC/tracker-control-android#51]
Blokada has this.

Yet, I don't have the resources to take on this project.

**Comment by xf-** [comment]
Is KDE Connect related to private DNS, because it is in local network? Allows to send a image or ping the phone. Also use the phone as remote for media or slides. It fails if Block is enabled for the app. I disabled it (no reason to block it, but i didn't expect the problem.)

(I didn't wanted to open a new issue if it is related and also disable works. Other local network apps are working fine.)

**Comment by kasnder** [comment]
> Is KDE Connect related to private DNS, because it is in local network?

I guess this is something else. Communication in the local network does not work with TrackerControl.

**Comment by kasnder** [comment]
Sorry!

**Comment by kasnder** [comment]
Closing this for now, since I'm working on port forwarding.
