### ISSUE TITLE
Add PrivacyBadger first / third party host discrimination

### ISSUE THREAD

**Issue by jawz101** [OxfordHCC/tracker-control-android#72]
If I open the Amazon Shopping app I expect the Amazon Shopping app to work.  The Facebook app to work. AccuWeather to work.

I cannot consider my consensual use of an app to be tracking.

And I wouldn't think the Disconnect list is a good source for anything but browser-based traffic.  That is why I made the MobileAdTrackers list, researched and contributed maybe 50 tracker signatures to the Exodus Privacy Project, and now maintain the Adaway list:  The mobile landscape has some crossover but is completely different than web landscape.  You're going to have more location tracking companies, sensor monitoring companies, Bluetooth Eddystone beacon junk, and the like.  The tracking is more based on having a device with 20+ sensors and 5 transceivers in everyone's pockets versus which clicks they make on a web page.

I love the idea.  I wish I could program Android apps.  I don't know of a clean way to address 1st vs 3rd party and also not rely on a static list.  I wish Android would require apps to declare which 3rd party companies have code within an app.

**Comment by kasnder** [comment]
The 1st v 3rd party problem is indeed challenging. I’m working on a method to block tracker communications, based upon the calling tracker library instead of the domain.

Disconnect is indeed not perfect. That’s why TrackerControl uses additionally our in-house X-Ray blocklist. Both lists, contrary to other ones, contain info on the company behind tracker.

If you want to use other lists, you can use custom block lists from the settings.

**Comment by jawz101** [comment]
How about keeping track of connections that happen by 3 or more apps?  Similar to how Privacy Badger does for web pages

**Comment by kasnder** [comment]
That’s great idea!

**Comment by kasnder** [comment]
I've now added a 'non-strict mode'. The aim is the same: allow some essential trackers and reduce breakage. The PrivacyBadger approach seems difficult because many tracker hosts might be called only by one app. Theoretically, one could think about bringing together multiple users. Yet, this raises privacy risks and is beyond my current capacity to manage the app.
